[package]
name = "contentline"
description = "A parser/encoder backend, which is useful to implement ical/vcf parsers/encoders"
version = "0.5.0"
authors = ["Markus Richter <mqus at disroot.org>"]
edition = "2018"
